-- MySQL Script generated by MySQL Workbench
-- Thu Jan  9 20:14:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_farmacia_bem_estar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_farmacia_bem_estar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_farmacia_bem_estar` DEFAULT CHARACTER SET utf8 ;
USE `db_farmacia_bem_estar` ;

-- -----------------------------------------------------
-- Table `db_farmacia_bem_estar`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_farmacia_bem_estar`.`tb_categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(500) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_farmacia_bem_estar`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_farmacia_bem_estar`.`tb_produtos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(500) NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  `validade` DATE NOT NULL,
  `fabricante` VARCHAR(500) NOT NULL,
  `tb_categorias_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produtos_tb_categorias_idx` (`tb_categorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_tb_categorias`
    FOREIGN KEY (`tb_categorias_id`)
    REFERENCES `db_farmacia_bem_estar`.`tb_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tb_categorias (tipo, descricao)
VALUES ('Medicamento', 'Produtos destinados ao tratamento de doenças e alívio de sintomas'),
('Cosmético', 'Produtos de beleza e cuidados pessoais'),
('Antisséptico', 'Produtos usados para prevenir infecções em ferimentos e cuidados de higiene'),
('Suplemento', 'Produtos alimentícios que auxiliam na suplementação nutricional'),
('Ortopédico', 'Produtos utilizados no auxílio ao tratamento de lesões ou problemas ortopédicos'),
('Gestante e Bebê', 'Produtos destinados a gestantes e cuidados com bebês, como vitaminas e pomadas'),
('Dietético', 'Alimentos e suplementos dietéticos para dietas específicas e restritivas'),
('Emergência e Primeiros Socorros', 'Produtos para primeiros socorros, como bandagens, ataduras, termômetro, etc.'),
('Higiene', 'Produtos de higiene pessoal e limpeza');

INSERT INTO tb_produtos (nome, preco, validade, fabricante, tb_categorias_id)
VALUES 
('Paracetamol 500mg', 15.00, '2025-12-31', 'Laboratório XYZ', 1),
('Ibuprofeno 400mg', 20.00, '2025-08-15', 'Laboratório ABC', 1),
('Shampoo Anti-resíduos', 25.00, '2024-12-31', 'Marca PQR', 2),
('Creme Hidratante Facial', 40.00, '2025-05-01', 'Marca DEF', 2),
('Álcool Gel 70%', 10.00, '2024-10-20', 'Antisséptico Ltda', 3),
('Sabonete Antisséptico', 8.00, '2025-04-10', 'Antisséptico Ltda', 3),
('Vitaminas A e D', 35.00, '2025-06-10', 'Nutri Pharma', 4),
('Whey Protein', 150.00, '2025-11-05', 'Nutri Pharma', 4),
('Gesso Ortopédico', 45.00, '2026-02-15', 'Ortopedika', 5),
('Colágeno Hidrolisado', 70.00, '2025-03-20', 'Ortopedika', 5),
('Ácido Fólico Gestante', 18.00, '2025-07-12', 'Gestante Pharma', 6),
('Pomada para Assaduras', 12.00, '2025-02-28', 'Gestante Pharma', 6),
('Leite em pó para Bebê', 30.00, '2025-09-01', 'Gestante Pharma', 6),
('Dieta Low Carb', 35.00, '2025-01-10', 'Nutri Foods', 7),
('Suco Detox', 20.00, '2025-06-15', 'Nutri Foods', 7),
('Termômetro Digital', 50.00, '2026-12-31', 'Health Devices', 8),
('Kit de Primeiros Socorros', 80.00, '2026-03-30', 'Health Devices', 8),
('Desodorante Roll-on', 15.00, '2024-11-10', 'Hygiene Pro', 9),
('Creme Dental', 5.00, '2025-12-25', 'Hygiene Pro', 9),
('Detergente Líquido', 3.50, '2024-06-05', 'CleanCo', 9),
('Tônico Capilar', 28.00, '2025-07-21', 'Marca XYZ', 2),
('Escova de Cabelos', 18.00, '2025-09-30', 'Marca XYZ', 2),
('Pomada para Dor Muscular', 20.00, '2025-11-12', 'Laboratório ABC', 1),
('Antibiótico Amoxicilina', 22.00, '2025-10-19', 'Laboratório XYZ', 1),
('Cotonete', 4.00, '2025-05-30', 'Hygiene Pro', 9),
('Creme Anti-rugas', 55.00, '2025-08-18', 'Marca PQR', 2);

SELECT * FROM tb_produtos;

SELECT nome AS Nome, CONCAT('R$', FORMAT(preco, 2, 'pt_BR')) AS Preço, Fabricante AS Fabricante
FROM tb_produtos 
WHERE preco >= 50.00
ORDER BY nome;

SELECT id AS Codigo,nome AS Nome,CONCAT('R$', FORMAT(preco, 2, 'pt_BR')) AS Preço, DATE_FORMAT(validade, '%d/%m/%Y') AS Validade
FROM tb_produtos 
WHERE preco BETWEEN 5.00 AND 60.00
ORDER BY id;

SELECT nome AS Nome, DATE_FORMAT(validade, '%d/%m/%Y') AS Validade, fabricante AS Fabricante 
FROM tb_produtos 
WHERE nome LIKE '%C%'
ORDER BY nome;

SELECT nome AS Nome, tipo AS Tipo, CONCAT('R$', FORMAT(preco, 2, 'pt_BR')) AS Preço, descricao AS Descrição
FROM tb_produtos 
INNER JOIN tb_categorias ON tb_produtos.tb_categorias_id = tb_categorias.id
ORDER BY nome;

SELECT nome AS Nome, tipo AS Tipo,  descricao AS Descrição, fabricante AS Fabricante
FROM tb_produtos 
INNER JOIN tb_categorias ON tb_produtos.tb_categorias_id = tb_categorias.id
ORDER BY nome;

SELECT nome AS Nome, tipo AS Tipo,fabricante AS Fabricante,  descricao AS Descrição, DATE_FORMAT(validade, '%d/%m/%Y') AS Validade
FROM tb_produtos 
INNER JOIN tb_categorias ON tb_produtos.tb_categorias_id = tb_categorias.id
WHERE tipo = 'Cosmético'
ORDER BY nome;